name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8
